name: Backup diario base de datos

on:
  schedule:
    - cron: '0 22 * * *'  # Corre todos los días a las 22:00 UTC
  workflow_dispatch:      # Permite ejecución manual

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install supabase

    - name: Ejecutar script backup
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
      run: |
        python backup_supabase_email.py
