name: Backup Diario

on:
  schedule:
    - cron: '0 3 * * *'  # Cada día a las 3 am UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar backup desde Render
      run: |
        curl -o database.db "https://web-registro-coches.onrender.com/download_backup?token=${{ secrets.API_TOKEN }}"

    - name: Instalar Python y dependencias
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Ejecutar script para enviar correo
      env:
        EMAIL_EMISOR: ${{ secrets.EMAIL_EMISOR }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEPTOR: ${{ secrets.EMAIL_RECEPTOR }}
      run: |
        python enviar_backup.py
